#ifndef _simpleloopselectionedge_H_
#define _simpleloopselectionedge_H_

enum
{
    // Menu IDs
    IDM_SIMPLELOOPSELECTIONEDGE_MENU1               = 900000, // c4d.FIRST_SIMPLELOOPSELECTIONEDGE_POPUP_SIMPLELOOPSELECTIONEDGE_ID
    IDM_SIMPLELOOPSELECTIONEDGE_MENU2               = 900010,    
    IDM_SIMPLELOOPSELECTIONEDGE_MENU3               = 900020,
        IDM_SIMPLELOOPSELECTIONEDGE_SUBMENU1        = 900021,
        IDM_SIMPLELOOPSELECTIONEDGE_SUBMENU2        = 900022,
        IDM_SIMPLELOOPSELECTIONEDGE_SUBMENU3        = 900023,
    IDM_SIMPLELOOPSELECTIONEDGE_MENU4               = 900030,
};

#endif